version: '3'

services:
  postgres_db:
    image: postgres:10
    ports:
      - '5432:5432'
    env_file:
      - '.env'
  subscription:
    build: '.'
    volumes:
      - .:/usr/src/subscription
      - /usr/src/subscription/node_modules
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    depends_on:
      - postgres_db
